### PR TITLE
Wpf UI redesign gizmohd

### PR DESCRIPTION
**Pull request by gizmohd**
THis is about 75% there I would figure... There are still some pieces that dont work just yet... namely the Authentication....  but that should be relatively simple to get working... I just ran out of time.. and after working on it all night.. My brain is a little frazzled.. :)

### CODE REVIEW

**Comment by isaacrlevin** [comment]
I didn't say work on it all night!!!! Thank you so much for helping out!!! I am speaking at .NET Conf today about PresenceLight, I will give you a name drop :)

**Comment by gizmohd** [comment]
Sounds good.. ;)

**Comment by isaacrlevin** [comment]
I just took your changes and added some UI fixes, so be sure to get a new PR when ready. It looks like there is an issue with Mediator and the SetColorCommand not being registered

**Comment by gizmohd** [comment]
I'll take a look at that this evening

**Comment by isaacrlevin** [comment]
I figured out that issue, but there seems to be a more sinister issue with settings savings. We might need to have a service at the Window level that gets updated and accessed. You can test by updating the Hue page and saving, and going to settings, update and save, THAN go back to Hue, and some settings aren't sticking.

**Pull request merged**
