### PR TITLE
Configuration and Logging Changes to better support Containerized Platforms

### PR DESCRIPTION
**Pull request by gizmohd**
While Nlog was a very good logging platform, it doesnt play as well with DotnetCore and the IConfiguration framework.   Serilog has much better support for configuration via json and/or Environment Variable overrides.. (especially when running within a container).  Nlog's xml based configuration is not as condusive to this.

Additionally, When running under containers, Especially in Kubernetes, having an additional path where configuration files can be read/written to that is outside of the container is especially helpful.

### CODE REVIEW

**Comment by isaacrlevin** [comment]
Love this PR!!! A Few thoughts

- I would like the log file location to be configurable via appsettings in both apps
  - Desktop version should default to local temp location (like it does now)
  - Worker should log to log directory at exe root
- I am making a bunch of changes in the Activity PR, make sure you merge that in soonish
  - #250
- Make sure the Serilog adapter for Application Insights is working as I send exceptions there
- Make the exception file logging a bit more robust as what I implemented is kinda flaky. I use a Helper function to log all things (as you know)

Super excited to see this, thanks!

**Comment by gizmohd** [comment]
Good news...   log file location is already  configurable  by changing the path in the appsettings.json..
image

I will get the application insights functionality plugged in right away... missed that part.. :)  Good news is Serilog is pretty great at logging stuff...   What, in your mind, equates to 'More Robust' for exception logging?

**Comment by isaacrlevin** [comment]
It seems at time, the actual exception message was not getting logged with my implementation, not sure if I swallow the actual exception or something, but since you are touching logging, might as well make it more clear for me when people have issues ;)

**Comment by gizmohd** [comment]
> It seems at time, the actual exception message was not getting logged with my implementation, not sure if I swallow the actual exception or something, but since you are touching logging, might as well make it more clear for me when people have issues ;)

FWIW,  I dont believe your 'helper' class is necessary with the new ILogger settings... Line and File become available in the stack trace.. but I will test more just to be sure..  before committing to replacing the helper.

**Comment by gizmohd** [comment]
Merged WIP - Custom Activity branch into this one.

**Comment by isaacrlevin** [comment]
@gizmohd is this ready for final review?

**Comment by gizmohd** [comment]
Yes

**Comment by gizmohd** [comment]
Anything left that's preventing you from merging?

**Comment by isaacrlevin** [comment]
Sorry been swamped with work. Can you revert the merge from the other PR branch? Once that is done, I will merge this in

**Comment by isaacrlevin** [comment]
Also LOVE the Logs tab, any chance this can be put in the Windows app?

**Comment by gizmohd** [comment]
Merge was reverted... Could have sworn you wanted that PR merged into this one.. ;)  Not sure where  I got that from.. but it was a lot of work.. :)   So.. I still have a branch with the changes necessary for the Merge... (there's a lot)... 

I will work on the App when I get a moment...   Work is also taking my time this week...

**Comment by isaacrlevin** [comment]
I asked you... I was expecting to get the activity work done but I have
been swamped at work

**Comment by isaacrlevin** [comment]
@gizmohd sorry to be a dick, but I got a chance this morning to complete activity presence support, so you will need to add back that commit :/

Or you can merge down from main :)

**Comment by gizmohd** [comment]
Okay.. resolved the conflicts and have pushed my changes to my master for the PR..

**Comment by isaacrlevin** [comment]
Sweet all looks good. Any news on exposing logs in wpf app?

**Comment by gizmohd** [comment]
Plan on working on it this weekend

**Comment by gizmohd** [comment]
I went ahead and closed my other PR and merged all my changes into this to make a single PR... 
Notable Changes:   includes logs tabs to mimic what is in the Worker.
image

Implemented the CQRS pattern to decouple the services from the pages that are calling them

**Pull request merged**
