### PR TITLE
Custom api body

### PR DESCRIPTION
**Pull request by stefanstranger**
I added the option to include a body message to the Custom API functionality.

image

Also have an update for the wiki configuration. Not sure how I share this update with you.

Regards,
Stefan Stranger

### CODE REVIEW

**Comment by isaacrlevin** [comment]
@stefanstranger looks like you didn't add the body to the appsettings.json and PresenceLightSettings.json files

**Comment by stefanstranger** [comment]
Updated the appsettings.json and PresenceLightSettings.json with body information

**Comment by stefanstranger** [comment]
I made a mistake to close the PR instead of the comment I wanted to close ;-)

**Comment by isaacrlevin** [comment]
@stefanstranger thanks for the contribution! Your changes are in the Nightly version, where you can test it out. Click this link to download the installer and run it.

https://presencelight.blob.core.windows.net/nightly/index.html

**Pull request merged**
