### PR TITLE
Added ability to select colour (or turn off) each availabilty status …

### PR DESCRIPTION
**Pull request by ben-pearson**
…for Philips Hue

Improvement for #77

### CODE REVIEW

**Comment by isaacrlevin** [comment]
This looks great! Ask, can you put screenshots into this PR as well so I can update the docs. Also, possibly look at using a color picker instead of pasting HEX?

**Comment by ben-pearson** [comment]
Yes! I actually meant to do a screen shot for you but I got distracted with life. 

I would have done colour pickers but that involved a bit too much learning Microsoft for me, so went with the MVP. I also meant to validate the fields but again can add that as an improvement later?

**Comment by isaacrlevin** [comment]
That's fine, as long as I can get some images. I'm going to add the color pickers in this branch before I merge it

**Comment by ben-pearson** [comment]
image

**Pull request merged**
