### PR TITLE
Configure ASP.NET Core to work with proxy servers and load balancers

### PR DESCRIPTION
**Pull request by BoBiene**
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-6.0

### CODE REVIEW

**Comment by isaacrlevin** [comment]
Thank you for the pull request! Can you give me a little information why you need this?

**Comment by BoBiene** [comment]
Hi @isaacrlevin,
shure. I'm using Traefik as reverseproxy and https offload on the Traefik side.
Since the communication between the Traefik and the ASP.Net Container is in HTTP i tried to setup the container without HTTPS. But then the redirect URL for the OIDC-Provdier gets changed to http from the configured https.

With this the container knows via the [X-Forwarded-For](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Forwarded-For) Header that the request came from a https endpoint.

**Comment by BoBiene** [comment]
Hi @isaacrlevin,
shure. I'm using treafik as reverseproxy and https offload on the traefik side.
Since the communication between the Treafik and the ASP.Net Container is in HTTP i tried to setup the container without HTTPS. But then the redirect URL for the OIDC-Provdier gets changed to http from the configured https.

With this the container knows via the [X-Forwarded-F](https://developer.mozilla.org/docs/Web/HTTP/Headers/X-Forwarded-For)

**Comment by isaacrlevin** [comment]
Have you made sure the web app works outside a container still?

**Comment by isaacrlevin** [comment]
Have you had a chance to check?

**Comment by BoBiene** [comment]
Sorry i currently don't have the time to setup this test. 
I'll try to check this next weekend

**Comment by isaacrlevin** [comment]
I tested on my side and it works, you were missing a using, but this is good to me. Thanks for the contribution!

**Comment by isaacrlevin** [comment]
FYI the containers are now updated with this change

**Pull request merged**
