### PR TITLE
Support for Yeelight and Xiaomi 

### PR DESCRIPTION
**Pull request by plkumar**
Hi @isaacrlevin 

I use Xiaomi/Yeelight LED Smart Bulb, added the support for the same, it works using the "YeelightAPI" nuget package, I thought it would help those who use these lights, hence submitting a PR.

https://www.mi.com/global/mi-led-smart-bulb

### CODE REVIEW

**Comment by plkumar** [comment]
Not sure of the check that is failed, let me know how to fix it, if it is related to my code.

**Comment by isaacrlevin** [comment]
It's not, it's a yaml issue, I'll fix it later. I can't test your functionality, so just let me know when you are done and I will test the UI changes

**Comment by isaacrlevin** [comment]
Can you pull latest and commit, want to trigger a working check from your side

**Comment by plkumar** [comment]
> Can you pull latest and commit, want to trigger a working check from your side

i've merged your latest changes, everything is looking good.

**Comment by isaacrlevin** [comment]
Awesome, thanks for the contribution!

**Comment by isaacrlevin** [comment]
@plkumar can you please add a PR to doc how to use Yeelight with the app now? I want to add it to the wiki

**Comment by plkumar** [comment]
@isaacrlevin i'm working on it, will submit the PR in few days, got busy with some work.

**Pull request merged**
