### PR TITLE
MQTT support

### PR DESCRIPTION
**Pull request by onpaj**

### CODE REVIEW

**Comment by isaacrlevin** [comment]
@onpaj any update here?

**Comment by isaacrlevin** [comment]
@onpaj can you please provide an update here?

**Comment by isaacrlevin** [comment]
@onpaj please provide an update

**Comment by Xyolyp** [comment]
@isaacrlevin I'd like to add to this pullrequest but I don't know how I can add some small commits. Should I create a new fork and a new pullrequest?

**Comment by isaacrlevin** [comment]
@onpaj do you intend to move forward with this PR?

also @Xyolyp you mentioned you were interested.

**Comment by isaacrlevin** [comment]
Closing PR has it seems interest in this has died down. More than happy to review if someone picks it up

**Pull request closed without merging**
