### PR TITLE
Add single URI custom API variant

### PR DESCRIPTION
**Pull request by Xyolyp**
Implement custom api flavor which allows to either get or post data to a single uri (with placeholder support for the uri and post body)
**User interface is completely missing!** 
This would allow the user to specify a single http uri (with support for placeholders for the values of the activity and availability in the uri and the body that will be sent via post)

The idea for this came from issue #150

### CODE REVIEW

**Comment by isaacrlevin** [comment]
@Xyolyp any update on this PR?

**Comment by Xyolyp** [comment]
@isaacrlevin I don't really have an idea on how to integrate this in the ui. If you have a suggestion or would implement the ui I would fix any issues that are found in the runtime.

**Comment by isaacrlevin** [comment]
This is how we did it on the WPF side, what do you think about this?
image

**Comment by BobBuildingCode** [comment]
Maybe just add another line at the top/bottom for single endpoint, something like this:
image

Also, I'm guessing that the body for the request will be something like the format that [Microsoft use](https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta#properties)? 
Example:
```json
{
   "availability":"Busy",
   "activity":"InACall"
}
```

Another thing, get shouldn't be an option for this, right? Since you probably only want to use post for sending the body.

**Comment by Xyolyp** [comment]
@BobBuildingCode the current draft for the runtime supports a custom payload with placeholders to enable the end user to use XML, JSON, CSV or whatever pattern they need and additionally the very same placeholders are supported for the endpoint which would allow using GET because the endpoint could change depending on the current activity and availability.

**Comment by onpaj** [comment]
Is there an option to send a custom body with each request type? 

How about custom headers (auth for example)?

**Comment by isaacrlevin** [comment]
Adding custom headers is something you would have to build yourself, I can't imagine it being too difficult

**Comment by isaacrlevin** [comment]
@Xyolyp any progress on the proposed UI?

**Comment by isaacrlevin** [comment]
Closing as I added this in #229

**Comment by gooman-uk** [comment]
@isaacrlevin any plans to implement this in the Windows Desktop version?

**Comment by isaacrlevin** [comment]
Feel free to open a new issue

**Comment by BobBuildingCode** [comment]
Is this really implemented? In the Web/Worker version I can only find "Custom API", which looks exactly like it always done in the Desktop version; with one endpoint for every status?

I can't find any way of configuring just one endpoint (one url) for all statuses? Or am I missing something?

**Pull request closed without merging**
