### PR TITLE
Working Hours

### PR DESCRIPTION
**Pull request by ross-p-smith**
Created a service that will work out whether we are outside of Working Hours and therefore whether to send events to the Custom Service. Hopefully, this should be the first part of #151

### CODE REVIEW

**Comment by isaacrlevin** [comment]
Few Issues I Found

- New Page Not Added To Nav
- Working Hours are not configurable

Page also fails when you go to customapi route

image

**Comment by ross-p-smith** [comment]
Yes sorry - never configured mine with the UI, I was just using the config file. I've wired up and prettified the existing page. I will add the Working Days and Times when I get a sec. But at least the page will render now

**Comment by isaacrlevin** [comment]
This looks great so far!

**Comment by isaacrlevin** [comment]
Hey there, any update here?

**Comment by isaacrlevin** [comment]
@ross-p-smith do you still plan on this PR?

**Comment by isaacrlevin** [comment]
Closing and moving work to #229

**Pull request closed without merging**
