### PR TITLE
Add custom api support to headless worker

### PR DESCRIPTION
**Pull request by Xyolyp**
Depends on #111 
Adds untested razor page for custom api configuration and adds custom api support to the headless worker

### CODE REVIEW

**Comment by Xyolyp** [comment]
I'm not sure what the correct target branch would be. This is the follow up to #111 and should add the user interface for the configuration of the custom ui to the web interface.
I was not able to get the blazor version running yet, therefor **_this is not tested_**.

**Comment by isaacrlevin** [comment]
Main branch has working code for the Worker version. What issues are you having?

**Comment by Xyolyp** [comment]
I currently don't have a running instance using the blazor pages but this pullrequest was my attempt to add the user interface for the changes made in #111 (adding the custom api urls for the activities). It's completely possible that I misinterpreted something as I have never worked with blazor before. If I overlooked something and the userinterface for the cusom api (without the changes of #111) is already present or maybe even autogenerated that no changes are required to enable the user to configure the new settings made available in #111 this pullrequest can be closed without merging.

**Comment by isaacrlevin** [comment]
Why did you modify the WPF app files if this is a PR for the Worker?

**Comment by Xyolyp** [comment]
I just pulled the addCustomApiSupportForActivity Branch to this one because I know it this way from bitbucket server. I did not know that the diff would ignore the merge that was performed inbetween.

**Comment by isaacrlevin** [comment]
So I can ignore those changes than?

**Comment by Xyolyp** [comment]
Yes you can ignore the changes made in the WPF app part.

**Pull request merged**
